version: '3.4'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: prisma_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  api:
    image: node:16.13.1 # バージョン指定も可能 ex. node:12.16.1
    container_name: prisma_sample
    tty: true
    volumes:
      - .:/prisma_sample
    working_dir: '/prisma_sample'
    ports:
      - '127.0.0.1:5555:5555'